require("config.autocmds")
require("config.keymaps")
require("config.lazy")
require("config.colorscheme")

require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.dashboard")
require("plugins.lualine")
require("plugins.noice")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.tree")
require("plugins.treesitter")
require("plugins.whichkey")
